// Re-export types from Zod schemas (single source of truth)
export type {
  DateRangeQuery,
  ProductSummary,
  FunnelStep,
  ProductFunnel,
  TopFeature,
  TopFeatures,
  TrendsQuery,
  TrendPoint,
  ProductTrends,
  HeatmapQuery,
  HeatmapCell,
  ProductHeatmap,
  TtvBucket,
  TtvStep,
  ProductTtv,
  CohortRetention,
  ProductCohort,
  ChannelSource,
  ChannelPostHog,
  ProductChannel,
  OnlineTimeRow,
  TouchpointRow,
  ProductOperational,
  StuckBusiness,
  ProductStuck,
} from '../schemas/dashboard-product.schema';
