version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smit_os_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smitos_db
    ports:
      - "5431:5432"
    volumes:
      - smit_os_db_data:/var/lib/postgresql/data

volumes:
  smit_os_db_data:
