services:
  db:
    image: postgres:15-alpine
    container_name: smit_os_db
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      POSTGRES_USER: smitos
      POSTGRES_PASSWORD: "change-me-local-only"
      POSTGRES_DB: smitos_db
    ports:
      - "5435:5432"
    volumes:
      - /Users/dominium/Documents/database:/var/lib/postgresql/data

# volumes:
#   smit_os_db_data:
#     driver: local
